baseURL = "https://nathanwillson.com/"
languageCode = "en-us"
title = "Nathan Willson"
disqusShortname = "nathanwillson-com"
googleAnalytics = "UA-119252446-1"

[markup.goldmark.renderer]
  unsafe= true

[params]
    flickr_api_key = "wGUikc8jnw6pbeqsvfSRMKkXzyjVpjF0"
    twitter_handle = "nathanwillson"
	email = "contact@nathanwillson.com"
	logo = "/images/logo.png"
    css  = [
    	"css/base.css",
    	"css/main.css",
    	"css/blog.css",
    	"css/music.css",
    	"css/design.css",
    	"css/project.css",
    	"css/header.css",
    	"css/footer.css"
    ]
  avg_wpm = 180.0

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

